logging_level: "INFO" # INFO is recommended
misp_servers:
 - domain: "https://misp-demo.es.net/" # <-- You MUST ADD YOUR OWN MISP URL HERE
   api_key: "My_MISP_API_key" #Â <-- You MUST ADD YOUR OWN MISP API KEY HERE
   verify_ssl: True # Switch to false to debug, stick to True in production
   debug: False 
   # misp.search() arguments
   args:
     enforce_warninglist: True 
   ioc_stagging:
     - tags:
         - "generic"
       max_age:
        # Date in MISP DateRestSearchFilter format [S,M,h,d,w,m,Y] or timestamp %Y-%m-%d %H:%M:%S
         ioc_date: 10d
     - tags:
         - "apt"
         - "tlp:amber"
       max_age:
         ioc_date: 1Y # 1 year of "tlp:amber" MISP IOCs
     - tags:
         - "SAFER"
       max_age:
         ioc_date: "2022-12-25 12:00:00" # All IOCs from after Xmas 2022 with the "SAFER" tag 

correlation: # use this if no files are defined from commmand line
  input_dir: /var/unicor/matches # This is were JSON input from dns-collector, Zeek, etc. goes
  output_dir: /var/unicor/alerts # Unicor correlate will produce alerts to be sent here
  alerts_database: /var/unicor/alerts_db.txt # Keep track of alerts sent and avoid duplicates for a while 
  alerts_database_max_size: 300 # This is how many alerts we keep in the buffer before re-notifying  
  malicious_domains_file: /var/unicor/misp_domains.txt # fetch-iocs will add domains from MISP here
  malicious_ips_file: /var/unicor/misp_ips.txt # fetch-iocs will add IPs from MISP here

alerting:
  max_alerts: 5 # Maximum number of alerts to be sent
  # At least one of the following needs to be enabled. Webhook is the prefered choice.
  messaging_webhook:  # Slack, Mattermost, Google Chat, etc.
     webhook: "https://hooks.slack.com/services/..." # <-- You MUST ADD YOUR OWN WEBHOOK
     template: "/etc/unicor/webhook.template"

#  telegram:
#    telegram_bot_token: "0123456789:AAAAA-AAAAA-AAAAAAAAAAA_AAAAAAAAAAA"
#    telegram_chat_id: "987654321"
#    template: "/etc/unicor/webhook.template"

# Note: Google Chat works just like Slack. Just add a Google Chat Webhook URL in the "slack_hook" above
#  email:
#    from: "security@your_org.net"
#    subject: "[Unicor] your_org DNS alert"
#    summary_to: "me@your_org.net"
#    server: "localhost"
#   port: 25
#    mappings:
#      - client_id: client_1
#        contact: client_1_sec_team@domain.tld

